version: '2.2'

services:
  lp-frontend-sipd:
    container_name: lp-frontend-sipd-container  # ← Nama container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9007:9007"
    env_file:
      - .env
    environment:
      - PORT=9007